Repository EasyWebApp/WebCell, pull requests merged in 2024-01, with the labels that each got.

#17 [refactor] rewrite WebCell 3 core API with latest ES/TS, MobX & vDOM
  .github/workflows/push.yml
  .gitignore
  .npmignore
  .npmrc
  Migrating.md
  ReadMe.md
  legacy/Async.tsx
  legacy/WebField.ts
  legacy/utility/MobX.ts
  legacy/utility/index.ts
  legacy/utility/polyfill.ts
  legacy/utility/vDOM.ts
  package.json
  pnpm-lock.yaml
  preview/.parcelrc
  preview/Clock.tsx
  preview/Home.tsx
  preview/index.html
  preview/index.tsx
  preview/package.json
  preview/tsconfig.json
  source/WebCell.tsx
  source/decorator.ts
  source/index.ts
  source/renderer.ts
  tsconfig.json
Labels: enhancement, feature

#19 [add] Quick Start document of WebCell v3
  ReadMe.md
  legacy/utility/MobX.ts
  package.json
  pnpm-lock.yaml
  preview/Async.tsx
  preview/Home.tsx
  preview/tsconfig.json
  source/Async.tsx
  source/MobX.ts
  source/WebCell.tsx
  source/decorator.ts
  source/index.ts
Labels: feature

#20 [add] Animate.css wrap component
  Contributing.md
  ReadMe.md
  package.json
  pnpm-lock.yaml
  preview/Home.tsx
  source/Animation/index.tsx
  source/Animation/type.ts
  source/Async.tsx
  source/MobX.ts
  source/decorator.ts
  source/index.ts
Labels: enhancement

#23 [chore] upgrade package, update husky config
  .husky/pre-commit
  .husky/pre-push
  package.json
  pnpm-lock.yaml
Labels: bug
